version: '3.8'

services:
    postgres:
#        container_name: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-odoo}
            POSTGRES_USER: ${POSTGRES_USER:-odoo}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
            PGDATA: /var/lib/postgresql/data/pgdata
        image: postgres:${POSTGRES_VERSION:-10}
        restart: always
        volumes:
          - postgres:/var/lib/postgresql/data/pgdata

    odoo-ce:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                ODOO_VERSION: ${ODOO_VERSION:-14.0}
                ODOO_RELEASE: ${ODOO_RELEASE:-20210427}
                ODOO_SHA: ${ODOO_SHA:-9d8e8038d5589bc8f4f5f012773dba4deefd3adc}
        command:
          - "--"
          - "--init=base"
          - "--database=${POSTGRES_DB:-odoo}"
#        container_name: odoo-ce
        depends_on:
          - postgres
        environment:
            HOST: postgres
            PORT: 5432
            USER: ${POSTGRES_USER:-odoo}
            PASSWORD: ${POSTGRES_PASSWORD:-odoo}
        ports:
          - ${ODOO_CE_PUBLISHED_PORT:-8069}:8069
        restart: always
        volumes:
#          - ./config:/etc/odoo
          - ./addons:/mnt/veone-addons
          - odoo-ce:/var/lib/odoo

    adminer:
        depends_on:
          - postgres
        image: adminer
        ports:
          - ${ADMINER_PUBLISHED_PORT:-9090}:8080
        restart: always

volumes:
    postgres:
    odoo-ce:
