# -*- coding: utf-8 -*-
{
    'name': "CRM & Ventes",

    'summary': """
        From quotations to invoices""",

    'description': """
        Manage sales quotations and orders extension
    """,

    'author': "VEONE",
    'website': "https://www.veone.net",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Opportunity to Quotation',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base', 'sale_crm', 'base_geolocalize','googlemap', 'document_sidebar', 'hr', 'sale', 'survey'],

    # always loaded
    'data': [
        'views/templates.xml',
        'security/sale_crm_security.xml',
        'security/ir.model.access.csv',
        'security/sale_crm_rules.xml',
        'data/mail_template.xml',
        'data/create_customer_email_template.xml',
        'data/sequence.xml',
        'data/enterprise_size_data.xml',
        'data/crm_lead_tag_data.xml',
        'data/cron_view.xml',
        'data/mail_tour_plan.xml',
        'data/campaign_email_template.xml',
        'data/sale_order_email_template.xml',
        'data/invoice_email_template.xml',
        'data/campaign_create_piste_email_template.xml',
        'data/study_email_template.xml',
        'wizards/reject_raison_view.xml',
        'wizards/standby_raison_view.xml',
        'views/config_views.xml',
        'wizards/create_lead_view.xml',
        'wizards/partner_update_view.xml',
        'views/crm_mail_activity_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_update_views.xml',
        'views/crm_team_views.xml',
        'views/contract_views.xml',
        'views/product_views.xml',
        'wizards/discount_reject_raison_view.xml',
        'wizards/dcm_discount_reject_raison_view.xml',
        'wizards/dga_discount_reject_raison_view.xml',
        'views/sale_order_expense_views.xml',
        'views/sale_order_evaluation_views.xml',
        'wizards/quotation_reject_raison_view.xml',
        'views/sale_order_template_views.xml',
        'views/sale_order_views.xml',
        'views/crm_stage_views.xml',
        'views/res_company_views.xml',
        'views/hr_employee_views.xml',
        'views/sale_year_views.xml',
        'views/sale_periodicity_views.xml',
        'views/account_move_views.xml',
        'views/sale_goal_views.xml',
        'views/survey_strategy_views.xml',
        'views/survey_question_views.xml',
        'views/survey_suspect_views.xml',
        'views/survey_region_views.xml',
        'views/survey_town_views.xml',
        'views/survey_commune_views.xml',
        'views/survey_campaign_nature_expense.xml',
        'views/crm_promotion_views.xml',
        'views/survey_out_media_type.xml',
        'views/survey_campaign_logistic.xml',
        'views/survey_campaign_report_views.xml',
        'views/survey_campaign_views.xml',
        'views/survey_media_type_views.xml',
        'views/survey_display_type_views.xml',
        'views/survey_target_views.xml',
        'views/survey_target_category_views.xml',
        'views/survey_target_under_category_views.xml',
        'views/survey_partner_views.xml',
        'views/survey_diffusion_type_views.xml',
        'views/survey_characteristic_views.xml',
        'views/survey_sub_characteristic_views.xml',
        'views/survey_info_characteristic_views.xml',
        'views/survey_csp_views.xml',
        'views/survey_personality_views.xml',
        'views/survey_study_level_views.xml',
        'views/survey_template_views.xml',
        'views/survey_views.xml',
        'views/crm_lead_views.xml',
        'views/crm_kpi_views.xml',
        'views/survey_culture_views.xml',
        'views/survey_religion_views.xml',
        'views/survey_purchase_frequency_views.xml',
        'views/survey_center_interest_views.xml',
        'views/survey_value_views.xml',
        'views/survey_age_views.xml',
        'views/survey_country_views.xml',
        "views/account_move_template_views.xml",
        'wizards/tour_plan_view.xml',
        'wizards/utm_sales_volume_view.xml',
        'wizards/utm_turnover_view.xml',
        "reports/report_view.xml",
        "reports/report_contract.xml",
        "reports/sale_goal_report_views.xml",
        "reports/report_tour_plan.xml",
        "reports/report_consolidated_tour_plan.xml",
        "reports/report_productivie_performence.xml",
        "reports/report_marketing_communication.xml",
        "reports/report_marketing_indicator.xml",
        "reports/report_promotion.xml",
        "reports/report_sale_order_template.xml",
        "reports/report_turnover_for_the_current_month.xml",
        "reports/report_turnover_for_the_current_month.xml",
        "reports/report_sales_volume.xml",
        "reports/report_account_move.xml",

    ],
    'qweb': [
        # 'static/src/css/*.css',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],

    'application': True,
}
